namespace WorkoutLogger.Entities
{
    public class Workout
    {
        public int Id { get; set; }

        /// <summary>
        /// Sync identity. Generated by whichever client created the workout, so a
        /// workout logged offline already has a stable id before the server has
        /// ever seen it. Retried syncs land on the same row instead of duplicating.
        ///
        /// The int Id stays the primary key: it keeps foreign keys compact and
        /// indexes unfragmented. This is what goes over the wire.
        /// </summary>
        public Guid PublicId { get; set; }

        public string Name { get; set; } = string.Empty;

        public TimeSpan? Duration { get; set; }

        /// <summary>When the workout happened.</summary>
        public DateTime Date { get; set; }

        public string Description { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Stamped server side on every write, never taken from the client. Clients
        /// use it as the delta-sync watermark, and it decides last-write-wins, so a
        /// phone with a skewed clock cannot win a conflict it should have lost.
        /// </summary>
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Tombstone. Deletes are recorded rather than executed so a delete made
        /// offline can propagate; a hard delete is invisible to other devices,
        /// which would happily resurrect the workout on their next sync.
        /// </summary>
        public DateTime? DeletedAt { get; set; }

        public int UserId { get; set; }
        public User? User { get; set; }

        public List<Exercise> Exercises { get; set; } = new();

        /// <summary>
        /// Watch recordings attached to this workout, if any. Usually zero or one,
        /// but a paused session can come back from the device as two.
        /// </summary>
        public List<Activity> Activities { get; set; } = new();
    }
}
